//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVolumePopulator) DeepCopyInto(out *AzureVolumePopulator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVolumePopulator.
func (in *AzureVolumePopulator) DeepCopy() *AzureVolumePopulator {
	if in == nil {
		return nil
	}
	out := new(AzureVolumePopulator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVolumePopulator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVolumePopulatorList) DeepCopyInto(out *AzureVolumePopulatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureVolumePopulator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVolumePopulatorList.
func (in *AzureVolumePopulatorList) DeepCopy() *AzureVolumePopulatorList {
	if in == nil {
		return nil
	}
	out := new(AzureVolumePopulatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVolumePopulatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVolumePopulatorSpec) DeepCopyInto(out *AzureVolumePopulatorSpec) {
	*out = *in
	out.BlobDownloadOptions = in.BlobDownloadOptions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVolumePopulatorSpec.
func (in *AzureVolumePopulatorSpec) DeepCopy() *AzureVolumePopulatorSpec {
	if in == nil {
		return nil
	}
	out := new(AzureVolumePopulatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlobDownloadOptions) DeepCopyInto(out *BlobDownloadOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlobDownloadOptions.
func (in *BlobDownloadOptions) DeepCopy() *BlobDownloadOptions {
	if in == nil {
		return nil
	}
	out := new(BlobDownloadOptions)
	in.DeepCopyInto(out)
	return out
}
