---
name: test (go)
on:
  push:
    branches:
      - master
  pull_request:
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Download
        run: go mod download all

      - name: Generate (fail when generated code is not committed)
        run: go generate -v ./... && git diff --exit-code ':!go.sum'

      - name: Build
        run: go build -v ./...

      - name: Unit Test
        run: |
          go test -v -race -shuffle=on -coverpkg "$(go list || go list -m | head -1)/..." -coverprofile cover.out.tmp ./...
