---
name: e2e-test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  end-to-end-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add hosts entry
        run: echo "127.0.0.1 local-registry" | sudo tee -a /etc/hosts

      # The provided example doubles as an end-to-end test.
      - name: E2E Test
        run: |
          docker compose -f ./example/docker-compose.yaml up
            --exit-code-from e2e-test
